---
title: "Lecture Schedule"
tbl-colwidths: [10, 90]
---

|`Lecture`| `Topic` |
|:---------:|:------------------------------------------------------------------------------|
| 1 | Introduction.  Basics of Probability (sample space, events, sigma-algebra of measurable sets, measurable space, measure, probability measure, non-measurable sets) |
| 2 | Random variables (discrete and continuous), indicators, distribution, expectation, absolute convergence, mean, variance, covariance, conditional probability, independence, law of total probability |
| 3 | Bernoulli process, binomial, geometric, negative binomial, convex functions, strict convexity, Jensen's inequality, entropy, cross-entropy, KL divergence |
| 4 | KL divergence (continued), hypergeometric distribution, exchangeability, tail sum formula |
| 5 | More on exchangeability and hypegeometric distribution, Boole's inequality (union bound), Cauchy-Schwarz inequality, Markov's inequality, Chebyshev's inequality, weak LLN |
| 6 | Convergence of Random Variables (almost sure convergence, convergence in probability, convergence in r-mean, convergence in distribution), strong LLN, CLT, equal in distribution vs equal in probability, examples of convergence |
| 7 | Convergence of Random Variables (continued), relations between different convergence concepts, moment generating function, applications to show convergence in distribution  (from Geometric to Exponential distribution; from Negative Binomial to Gamma distribution) |
| 8 | Sums of random variables, convolution, empirical cumulative distribution function, Glivenko-Cantelli Theorem, Chernoff Inequalities, bounded random variables, Hoeffding's inequality |
| 9 | Proof of Hoeffding's inequality, sub-Gaussian random variables, Hoeffding's lemma, entropy approximation of Binomial, normal approximation of Binomial, Proof of CLT for sums of Bernoulli random variables |
| 10 | A sum of independent normal RVs, application of the CLT, proof of the CLT, Berry-Eseen Theorem, Extensions of CLT |
| 11 | Characteristic function, Levy's continuity theorem, from binomial to Poisson, multinomial distribution, Poissonization of the multinomial, probability generating function (PGF), compounding |
| 12 | Transformation of a single RV, invertible vs. non-invertible transformations, one-to-one differentiable transformations, many-to-one transformations, Cauchy distribution, log-normal distribution, chi-square/gamma distribution, chi distribution, quantile transform, quantile function | 
| 13 | Bivariate jointly continuous random variables, bivariate normal, marginal densities, polar coordinates, linear transformations, invertible linear transformations, rotations, orthogonal transformations | 
| 14 | Joint density, independence, review of invertible affine transformations, general invertible transformations, gamma and beta distributions |
| 15 | Beta distribution, Dirichlet distribution, order statistics, CDF and PDF of the $j$th order statistics, uniform order statistics, general order statistics via quantile transformation, joint distribution of order statistics, gaps (spacings), exchangeability |
| 16 | Linear models, MLE of regression coefficients, hypothesis testing, conditional densities of continuous RVs, independence of continuous RVs, Law of Total Probability for continuous RVs, Cauchy, t-distribution, Bayes Rule for continuous RVs |
| 17 | Bayesian inference, conjugate priors for binomial and multinomial distributions, conjugate priors for Normal random variables, model selection, prior odds, Bayes factor, posterior odds |
| 18 | Conditional expectation, law of total expectation (aka law of iterated expectation, tower property), Wald's identity, statistical risk minimization, MSE, MAE |
| 19 | Jointly normal/Gaussian RVs (a.k.a., multivariate normal), covariance matrices, PDF of multivariate normal distribution, bivariate normal example, marginal distribution of multivariate normal, conditional distribution of multivariate normal |
| 20 | Positive (semi-)definite matrices, moment generating function for multivariate normal, idempotent matrices, relation between multivariate normal and chi-square distributions, multivariate CLT, Pearson's chi-square test |
| 21 | Guassian processes, covariance function (kernel), stationary kernels, isotropic kernels, sampling from GP, regularization (nugget), radial basis function, Matérn kernel, Browning motion, Brownian bridge, Ornstein-Uhlenbeck kernel, linear kernel, predictions from GP | 
| 22 | Proof of the Glivenko-Cantelli theorem (weak version), convergence of the empirical process to the Brownian bridge, Kolmogorov-Smirnov distribution |
| 23 | Stochastic/random process, Galton-Watson branching process $\{X_t, t\in \mathbb{N}_0\}$, offspring distribution, $\mathbb{E}[X_t]$, $\text{Var}[X_t]$, super-criticality, criticality, sub-criticality, extinction probability via probability generating function, extinction time distribution  |
| 24 | Discrete-time Markov chain, transition probability, homogeneity, $n$-step transition probability, Chapman-Kolmogorov equation, classification of states, irreducible Markov chain, first passage probability, return probability, mean recurrence time, recurrent/persistent states, transient states, first-step analysis, hitting probability, hitting time,  stationary distribution, existence and uniqueness |
| 25 | The long-term behavior of Markov chains, period, regular/ergodic Markov chains, limiting distributions, WLLN for irreducible finite Markov chains, ergodic theorem, fundamental matrix of irreducible Markov chains, mean first passage times, reversed process, reversibility, detailed balance |
| 26 | Continuous-time Markov chain, standard transition matrices, generator, stable Markov chains, conservative Markov chains, Kolmogorov Forward Equation, Kolmogorov Backward Equation, holding time distributions, Poisson Process, Birth-Death processes, jump process/jump chain/embedded chain |
