---
title: "Syllabus"
---

Jump to:

- [About Stat 201A](#about)
  - [Course Description](#course)
  - [Textbook](#textbook)
  - [Prerequisites](#prerequisites)
- [Course Policies](#course)
  - [Technology](#technology)
  - [Grading](#grading)
  - [Exams](#exams)
  - [Cheating](#cheating)
  - [Collaboration](#collaboration)

## About Stat 201A

### Course Description

This course will cover the fundamentals of probability theory at an advance level.  Upon reviewing basic undergraduate probability, we will study various topics, including concentration inequalities, convergence of random variables, generating functions, limit theorems, multivariate random variables, and stochastic processes.

### Textbook

There is no required textbook for the class.  You may use the following books as general references:

- *An Intermediate Course in Probability, 2nd edition* by Allan Gut
- *Stochastic Processes: Theory for Applications* by Robert G. Gallager

### Prerequisites

- Undergraduate probability (at the level of Berkeley’s Statistics 134)
- Multivariable calculus (at the level of Berkeley’s Mathematics 53) 
- Linear algebra (at the level of Berkeley’s Mathematics 54)

## COURSE POLICIES

### Technology

#### Ed Discussion

We will use Ed Discussion as the 'one-stop shop' throughout the semester: for a Q&A forum and for official announcements. Enrollment in Ed Discussion is mandatory. If you have questions about anything related to the course, please post them on Ed Discussion rather than emailing the instructor or TAs. Please do not post anything resembling a solution to a homework problem before it's due. We always welcome any feedback on what we could be doing better. See the Ed Discussion Etiquette section for more on using Ed Discussion. Ed Discussion can be accessed through bCourses.

#### Gradescope

All homework will be submitted through Gradescope, and all homework and exam grades will be returned through Gradescope.

#### Email

Please use Ed Discussion for all technical questions, and also all administrative questions about the course that are not personal to you: other students may also benefit from seeing the answers to these questions. If you have a more specific administrative question that relates to you alone, please either use a private post on Ed Discussion (visible to course staff only) or send email to the course administrative account `stat201a-fa24@lists.berkeley.edu`  (read by the instructor and TA).  Your e-mail must be sent from a Berkeley e-mail address; otherwise, it will get rejected automatically.

### Grading

Grades will be determined according to the following weighting of problem sets and exam scores:

- Homework: 50%
- Midterm: 20%
- Final: 30%

NOTE: We will drop the lowest homework score.

### Late Homework Policy
Your lowest homework score will be dropped, but this drop should be reserved for emergencies. No additional allowances will be made for late or missed homework: please do not contact us about missed homework or late submissions.

### Exams

Midterm is on Thursday, October 17, in class.  The Final is on Friday, December 20, 2024, 7-10pm. We are unable to accommodate exam conflicts; we strongly discourage enrollment in another class with conflicting lectures and/or final exam; if you choose to enroll in such a class you will have to make arrangements for an alternate Final with the other class.  

### Cheating

We have a zero-tolerance policy for cheating. Consequences of cheating include: negative points for the corresponding assignment, a failing grade in the class, and/or a referral to the Office of Student Conduct.

### Collaboration

You are welcome to work on homework problems in study groups of two to four people; however, you must always write up the solutions on your own. Similarly, you may use books or online resources to help solve homework problems, but you must always credit all such sources in your writeup and you must never copy material verbatim.

We believe that most students can distinguish between helping other students and cheating. Explaining the meaning of a question, discussing a way of approaching a solution, or collaboratively exploring how to solve a problem within your group are types of interaction that we strongly encourage. But you should write your homework solution strictly by yourself so that your hands and eyes can help you internalize this material. At no time should you be in possession of another student's solution. You may discuss approaches but your solution must be written by you and you only. You should acknowledge everyone whom you have worked with or who has given you any significant ideas about the homework. Not only is this good scholarly conduct, it also protects you from accusations of being a "free-rider" regarding your colleagues' ideas.

Warning: Your attention is drawn to Berkeley Honor Code: 

> “As a member of the UC Berkeley community, I act with honesty, integrity, and respect for others.”

In particular, you should be aware that copying or sharing solutions, in whole or in part, from other students in the class (or any other source without acknowledgment) constitutes cheating.  Any student found to be cheating risks automatically failing the class and being referred to the Office of Student Conduct.

